// Mock bike data - Wrocław, Poland area
const mockBikes = [
  {
    id_roweru: "1",
    kod_qr: "BIKE-00001",
    status: "AVAILABLE",
    poziom_baterii: 85,
    lokalizacja_szerokosc: 51.108,
    lokalizacja_dlugosc: 17.039,
    zasieg_km: 25,
  },
  {
    id_roweru: "2",
    kod_qr: "BIKE-00002",
    status: "AVAILABLE",
    poziom_baterii: 92,
    lokalizacja_szerokosc: 51.1095,
    lokalizacja_dlugosc: 17.032,
    zasieg_km: 30,
  },
  {
    id_roweru: "3",
    kod_qr: "BIKE-00003",
    status: "RENTED",
    poziom_baterii: 60,
    lokalizacja_szerokosc: 51.1075,
    lokalizacja_dlugosc: 17.038,
    zasieg_km: 18,
  },
  {
    id_roweru: "4",
    kod_qr: "BIKE-00004",
    status: "AVAILABLE",
    poziom_baterii: 78,
    lokalizacja_szerokosc: 51.105,
    lokalizacja_dlugosc: 17.041,
    zasieg_km: 22,
  },
  {
    id_roweru: "5",
    kod_qr: "BIKE-00005",
    status: "BROKEN",
    poziom_baterii: 15,
    lokalizacja_szerokosc: 51.111,
    lokalizacja_dlugosc: 17.028,
    zasieg_km: 5,
  },
  {
    id_roweru: "6",
    kod_qr: "BIKE-00006",
    status: "RESERVED",
    poziom_baterii: 70,
    lokalizacja_szerokosc: 51.1065,
    lokalizacja_dlugosc: 17.045,
    zasieg_km: 20,
  },
  {
    id_roweru: "7",
    kod_qr: "BIKE-00007",
    status: "AVAILABLE",
    lokalizacja_szerokosc: 51.102,
    lokalizacja_dlugosc: 17.035,
  },
  {
    id_roweru: "8",
    kod_qr: "BIKE-00008",
    status: "AVAILABLE",
    poziom_baterii: 88,
    lokalizacja_szerokosc: 51.113,
    lokalizacja_dlugosc: 17.04,
    zasieg_km: 28,
  },
];

module.exports = mockBikes;
